Quiebre del pipeline pos SAST

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -71,28 +71,39 @@ jobs:
               run: |
 
                 # curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/ce/component?component=${{ github.event.repository.name }}')
-                idanalisis=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/ce/component?component=${{ github.event.repository.name }}')
-                idanalisisParse=$(echo "$idanalisis" | jq .current.analysisId | sed -e 's/^"//' -e 's/"$//')
-                echo "Id del análisis sonarwqube $idanalisisParse"
-                qualitygate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/qualitygates/project_status?analysisId=$idanalisisParse')
-                qualitygatesStatus=$(echo "$qualitygate" | jq .projectStatus.status | sed -e 's/^"//' -e 's/"$//')
-                case $qualitygateStatus in
-                  *"OK"*)
-                    echo "Calidad del código OK"
-                  ;;
-                  *"ERROR"*)
-                    echo "Calidad del código ERROR"
-                    exit 1
-                    ;;
-                  *"WARN"*)
-                    echo "Calidad del código WARN"
-                    exit 1
-                    ;;
-                  *"NONE"*)
-                    echo "Estado NONE de la calidad del codigo $qualitygateStatus"
-                    exit 1
-                    ;;
-                esac  
+                # idanalisis=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/ce/component?component=${{ github.event.repository.name }}')
+                # idanalisisParse=$(echo "$idanalisis" | jq .current.analysisId | sed -e 's/^"//' -e 's/"$//')
+                # echo "Id del análisis sonarwqube $idanalisisParse"
+                # qualitygate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/qualitygates/project_status?analysisId=$idanalisisParse')
+                # qualitygatesStatus=$(echo "$qualitygate" | jq .projectStatus.status | sed -e 's/^"//' -e 's/"$//')
+                # case $qualitygateStatus in
+                #   *"OK"*)
+                #     echo "Calidad del código OK"
+                #   ;;
+                #   *"ERROR"*)
+                #     echo "Calidad del código ERROR"
+                #     exit 1
+                #     ;;
+                #   *"WARN"*)
+                #     echo "Calidad del código WARN"
+                #     exit 1
+                #     ;;
+                #   *"NONE"*)
+                #     echo "Estado NONE de la calidad del codigo $qualitygateStatus"
+                #     exit 1
+                #     ;;
+                # esac
+                
+                issuesvalidate=$(curl -s-X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarclud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}'&facets=severities' | jq .facets[0].values[1].Count  )
+                if [ "$issuesvalidate" -gt 0 ];
+                then
+                  echo "Existen dificultades en el código, abortar Pipeline"
+                  exit 1
+                else
+                  echo "Continua Pipeline, código correcto"
+                fi
+
+                
     SCA:
       needs: SAST
       runs-on: ubuntu-latest
