Docker Image Login y Push

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -22,57 +22,57 @@ jobs:
             - name: Build React
               run: npm run build
                 
-            - name: Validando existencia del proyecto en SonarQube
-              run: |
-                set +e
-                curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{github.event.repository.name}}' -d 'project=${{github.event.repository.name}}' -d 'organization=franciscopainemal' -d 'visibility=public'
-                if [ $? -ne 0 ]; then
-                    echo "el proyecto ya existe en SonarCloud"
-                    echo ":: set-output name=proyectoExiste::1"
-                else
-                    echo "Proyecto ${{github.event.repository.name}} creado exitosamente con SonarCloud"
-                    echo "Se establece rama Main como rama por defecto"
-                    curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'                
-                fi
-                set -e
+            # - name: Validando existencia del proyecto en SonarQube
+            #   run: |
+            #     set +e
+            #     curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{github.event.repository.name}}' -d 'project=${{github.event.repository.name}}' -d 'organization=franciscopainemal' -d 'visibility=public'
+            #     if [ $? -ne 0 ]; then
+            #         echo "el proyecto ya existe en SonarCloud"
+            #         echo ":: set-output name=proyectoExiste::1"
+            #     else
+            #         echo "Proyecto ${{github.event.repository.name}} creado exitosamente con SonarCloud"
+            #         echo "Se establece rama Main como rama por defecto"
+            #         curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'                
+            #     fi
+            #     set -e
 
-            -  name: Validando el tipo de proyecto
-               run: | 
-                if [ -f "package.json" ]; 
-                then    
-                    if grep -q '"react"' package.json 
-                    then
-                        echo "Proyecto es React."
-                    else   
-                        echo "El proyecto no es del tipp React."
-                        exit 1
-                    fi
-                else 
-                    echo "No se encontró archivo."
-                    exit 1
-                fi
-            - name: Ejecutando SonarCloud
-              run: |
-                npx sonar-scanner \
-                  -Dsonar.projectKey=${{ github.event.repository.name }} \
-                  -Dsonar.organization=franciscopainemal \
-                  -Dsonar.host.url=https://sonarcloud.io \
-                  -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
-                  -Dsonar.branch.name=main
+            # -  name: Validando el tipo de proyecto
+            #    run: | 
+            #     if [ -f "package.json" ]; 
+            #     then    
+            #         if grep -q '"react"' package.json 
+            #         then
+            #             echo "Proyecto es React."
+            #         else   
+            #             echo "El proyecto no es del tipp React."
+            #             exit 1
+            #         fi
+            #     else 
+            #         echo "No se encontró archivo."
+            #         exit 1
+            #     fi
+            # - name: Ejecutando SonarCloud
+            #   run: |
+            #     npx sonar-scanner \
+            #       -Dsonar.projectKey=${{ github.event.repository.name }} \
+            #       -Dsonar.organization=franciscopainemal \
+            #       -Dsonar.host.url=https://sonarcloud.io \
+            #       -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
+            #       -Dsonar.branch.name=main
 
-            - name: Validando resultados de SonarQube
-              run: |
-                issuesCritical=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}&facets=severities' | jq '.facets[0].values[2].count')
-                issuesMayor=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}&facets=severities' | jq '.facets[0].values[1].count')
-                issuesMinor=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}&facets=severities' | jq '.facets[0].values[0].count')
+            # - name: Validando resultados de SonarQube
+            #   run: |
+            #     issuesCritical=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}&facets=severities' | jq '.facets[0].values[2].count')
+            #     issuesMayor=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}&facets=severities' | jq '.facets[0].values[1].count')
+            #     issuesMinor=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}&facets=severities' | jq '.facets[0].values[0].count')
                                             
-                if [ "$issuesCritical" -gt 0 ] || [ "$issuesMayor" -gt 0 ] || [ "$issuesMinor" -gt 0 ];
-                then
-                  echo "Existen infracciones de niveles Criticos, Mayores y/o Medios en el código, se aborta Pipeline"
-                  # exit 1
-                else
-                  echo "Continua Pipeline"
-                fi
+            #     if [ "$issuesCritical" -gt 0 ] || [ "$issuesMayor" -gt 0 ] || [ "$issuesMinor" -gt 0 ];
+            #     then
+            #       echo "Existen infracciones de niveles Criticos, Mayores y/o Medios en el código, se aborta Pipeline"
+            #       # exit 1
+            #     else
+            #       echo "Continua Pipeline"
+            #     fi
 # ----------------------------  Análisis de dependencias SCA-------------------------------------                
     SCA:
       needs: SAST
@@ -92,41 +92,28 @@ jobs:
       - name: Build React
         run: npm run build
       
-      - name: Dependency Check
-        uses: dependency-check/Dependency-Check_Action@1.1.0
-        env:
-          REACT_HOME: /foo
-        with:
-          project: '${{ github.event.repository.name }}'
-          path: '.'
-          format: 'HTML'
-          out: 'reports'
-          args: > 
-            --failOnCVSS 7
-            --enableRetired
+      # - name: Dependency Check
+      #   uses: dependency-check/Dependency-Check_Action@1.1.0
+      #   env:
+      #     REACT_HOME: /foo
+      #   with:
+      #     project: '${{ github.event.repository.name }}'
+      #     path: '.'
+      #     format: 'HTML'
+      #     out: 'reports'
+      #     args: > 
+      #       --failOnCVSS 7
+      #       --enableRetired
       
-      - name: Generar reporte Dependency Check
-        uses: actions/upload-artifact@v4
-        with:
-          name: dependency-check-reports
-          path: ${{ github.workspace }}/reports
+      # - name: Generar reporte Dependency Check
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: dependency-check-reports
+      #     path: ${{ github.workspace }}/reports
 
 # ----------------------------  Subir repo a Docker -------------------------------------
     UPLOADDOCKER:
       needs: SCA
-      # runs-on: ubuntu-latest
-      # steps:
-      # - uses: actions/checkout@v2
-      # - uses: actions/setup-node@v4
-      #   with:
-      #     node-version: 18
-      # - run: npm ci
-      # - run: npm run build
-      # - name: Upload React Build
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: react-build
-      #     path: ./build
       runs-on: ubuntu-latest
       steps:
       - name: Checkout código
@@ -160,35 +147,35 @@ jobs:
 
 
 # ----------------------------  descargar repo a Docker -------------------------------------
-    # DOCKERBUILD:
-    #   needs: UPLOADDOCKER
-    #   runs-on: ubuntu-latest
-    #   steps:
-    #   - name: Checkout code
-    #     uses: actions/checkout@v2
+    DOCKERBUILD:
+      needs: UPLOADDOCKER
+      runs-on: ubuntu-latest
+      steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
         
-    #   - name: Download React Build
-    #     uses: actions/download-artifact@v4
-    #     with:
-    #       name: react-build
-    #       path: ${{ github.workspace }}
+      - name: Download Next.js Build
+        uses: actions/download-artifact@v4
+        with:
+          name: next-build
+          path: .
 
-    #   - name: Verificar contenido
-    #     run: ls -la ./build
+      - name: Verificar contenido
+        run: ls -la ./build
       
-    #   - name: Docker Login
-    #     uses: docker/login-action@v3.0.0
-    #     with:
-    #       username: ${{ secrets.DOCKER_USER }}
-    #       password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Docker Login
+        uses: docker/login-action@v3.0.0
+        with:
+          username: ${{ secrets.DOCKER_USER }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    #   - name: Build Docker Image
-    #     run: |
-    #       docker build --tag wainerock/devsecopslab-test:latest .
+      - name: Build Docker Image
+        run: |
+          docker build --tag wainerock/devsecopslab-test:latest .
 
-    #   - name: Push Docker Image
-    #     run: |
-    #       docker push wainerock/devsecopslab-test
+      - name: Push Docker Image
+        run: |
+          docker push wainerock/devsecopslab-test
 
         
           
