Análisis SCA y generación de reporte como artefacto

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -95,7 +95,7 @@ jobs:
                                         
             if [ "$issuesCritical" -gt 0 ] || [ "$issuesMayor" -gt 0 ] || [ "$issuesMinor" -gt 0 ];
             then
-              echo "Existen infracciones de niveles Criticos, Mayores y/o Medios en el código, se aborta Pipeline"
+              echo "Existen infracciones de niveles Criticos, Mayores y/o Medios en el código, se aborta Pipeline en el análisis SAST"
               # exit 1
             fi
 
@@ -132,7 +132,7 @@ jobs:
               name: dependency-check-reports
               path: ${{ github.workspace }}/reports
               
-        - name: Mostrar resumen de vulnerabilidades
+        - name: Mostrar vulnerabilidades encontradas
           run: |
             echo "Analizando reporte JSON..."
             REPORT="reports/dependency-check-report.json"
@@ -148,9 +148,15 @@ jobs:
             MEDIUM=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "moderate")] | length' "$REPORT")
             TOTAL=$(jq '[.dependencies[].vulnerabilities[]?] | length' "$REPORT")
 
-            echo "Vulnerabilidades encontradas:"
-            echo "Críticas: $CRITICAL"
-            echo "Altas: $HIGH"
-            echo "Medias: $MEDIUM"
-            echo "Bajas: $LOW"
-            echo "Total: $TOTAL"
+            echo "Vulnerabilidades encontradas críticas: $CRITICAL; altas: $HIGH; y medias: $MEDIUM; con tun total de: $TOTAL"
+            # echo "Críticas: $CRITICAL"
+            # echo "Altas: $HIGH"
+            # echo "Medias: $MEDIUM"
+            # echo "Bajas: $LOW"
+            # echo "Total: $TOTAL"
+            
+            if [ "CRITICAL" -gt 0 ] || [ "HIGH" -gt 0 ] ||  [ "MEDIUM" -gt 0 ];
+            then
+              echo "Existen infracciones de niveles Criticos, Mayores y/o Medios en el código, se aborta Pipeline en el análisis SCA"
+              exit 1
+            fi
