Análisis SCA y generación de reporte como artefacto

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -95,7 +95,7 @@ jobs:
                                         
             if [ "$issuesCritical" -gt 0 ] || [ "$issuesMayor" -gt 0 ] || [ "$issuesMinor" -gt 0 ];
             then
-              echo "Existen infracciones de niveles Criticos, Mayores y/o Medios en el código, se aborta Pipeline en el análisis SAST"
+              echo "Existen infracciones de niveles Críticas, Altas y/o Medias en el código, se aborta Pipeline en el análisis SAST"
               # exit 1
             fi
 
@@ -132,7 +132,7 @@ jobs:
               name: dependency-check-reports
               path: ${{ github.workspace }}/reports
               
-        - name: Mostrar vulnerabilidades encontradas
+        - name: Mostrar vulnerabilidades encontradas del reporte.json
           run: |
             echo "Analizando reporte JSON..."
             REPORT="reports/dependency-check-report.json"
@@ -140,18 +140,40 @@ jobs:
             if [ ! -f "$REPORT" ]; 
             then
               echo "No se encontró el reporte JSON en $REPORT"
-              exit 1
+              # exit 1
             fi
 
             CRITICAL=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "critical")] | length' "$REPORT")
             HIGH=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "high")] | length' "$REPORT")
             MEDIUM=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "moderate")] | length' "$REPORT")
-            TOTAL=$(jq '[.dependencies[].vulnerabilities[]?] | length' "$REPORT")
-
-            echo "Vulnerabilidades encontradas críticas: $CRITICAL; altas: $HIGH; y medias: $MEDIUM;"
             
             if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ] ||  [ "$MEDIUM" -gt 0 ];
             then
-              echo "Existen infracciones de niveles Criticos, Mayores y/o Medios en el código, se aborta Pipeline en el análisis SCA"
-              exit 1
+              echo "Vulnerabilidades encontradas críticas: $CRITICAL; altas: $HIGH; y medias: $MEDIUM;"
+              echo "Existen infracciones de niveles Críticas, Altas y/o Medias en el código, se aborta Pipeline en el análisis SCA"
+              # exit 1
             fi
+            
+# CONSTRUCCIÓN DE IMAGEN, quiebre de pipeline 
+  DOCKERBUILD:
+      needs: SCA
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v2
+        
+        - name: Descargar Artefacto Build
+          uses: actions/download-artifact@master
+          with:
+              name: build-artifact
+              path: .
+
+        - name: Docker Login
+          uses: docker/login-action@v3.0.0
+          with:
+            username: ${{ secrets.DOCKER_USER }}
+            password: ${{ secrets.DOCKER_PASSWORD }}
+
+        - name: Build Imagen Docker
+          run: |
+            docker build --tag wainerock/devsecopslab-test:latest .
