Escaneo DAST con OWASP ZAP scan

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -196,114 +196,114 @@ jobs:
 
 # ----------------------------  Escanear a DAST -------------------------------------
  
-    # DAST:
-    #   needs: SCANDOCKER
-    #   runs-on: self-hosted
-    #   steps:
-      
-    #   # - name: Permitir ejecución de scripts
-    #   #   shell: bash
-    #   #   run: |
-    #   #     Set-ExecutionPolicy Bypass -Scope Process -Force
-
-    #   # - name: Despliegue App
-    #   #   shell: pwsh
-    #   #   run: |
-    #   #     docker run -p 3000:3000 --name laboratorio-final-deploy -d wainerock/devsecopslab-test:latest
-
-    #   # - name: Esperando...
-    #   #   run: |
-    #   #     sleep 10
-    #   #     curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3000 || exit 1
-      
-    #   # - name: Escanear con OWASP ZAP Scan
-    #   #   uses: zaproxy/action-baseline@v0.11.0
-    #   #   with:
-    #   #     target: 'http://localhost:3000/' 
-    #   - name: Eliminar contenedor previo si existe
-    #     shell: powershell
-    #     run: |
-    #       Write-Host "Intentando eliminar contenedor existente (si hay)..."
-    #       try {
-    #         docker rm -f laboratorio-final-deploy | Out-Null
-    #         Write-Host "Contenedor eliminado"
-    #       } catch {
-    #         Write-Host "No se eliminó ningún contenedor (posiblemente no existe)"
-    #       }
-
-    #   - name: Desplegar contenedor de aplicación
-    #     shell: powershell
-    #     run: |
-    #       Write-Host " Iniciando contenedor..."
-    #       docker run -p 3000:3000 --name laboratorio-final-deploy -d wainerock/devsecopslab-test:latest
-
-    #   - name: Escanear con OWASP ZAP (DAST)
-    #     uses: zaproxy/action-baseline@v0.11.0
-    #     with:
-    #       target: 'http://localhost:3000/'
-    #       fail_action: false
-    #       # rules_file_name: '' ##
-          # cmd_options: '-config replacer.full_list(0).enabled=false'
-
-      # - name: Eliminar contenedor de aplicación (cleanup)
-      #   if: always()
-      #   shell: powershell
-      #   run: |
-      #     Write-Host "Eliminando contenedor laboratorio-final-deploy..."
-      #     docker rm -f laboratorio-final-deploy | Out-Null
-
     DAST:
       needs: SCANDOCKER
       runs-on: self-hosted
-
       steps:
+      
+      # - name: Permitir ejecución de scripts
+      #   shell: bash
+      #   run: |
+      #     Set-ExecutionPolicy Bypass -Scope Process -Force
+
+      # - name: Despliegue App
+      #   shell: pwsh
+      #   run: |
+      #     docker run -p 3000:3000 --name laboratorio-final-deploy -d wainerock/devsecopslab-test:latest
+
+      # - name: Esperando...
+      #   run: |
+      #     sleep 10
+      #     curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3000 || exit 1
+      
+      # - name: Escanear con OWASP ZAP Scan
+      #   uses: zaproxy/action-baseline@v0.11.0
+      #   with:
+      #     target: 'http://localhost:3000/' 
+      - name: Eliminar contenedor previo si existe
+        shell: powershell
+        run: |
+          Write-Host "Intentando eliminar contenedor existente (si hay)..."
+          try {
+            docker rm -f laboratorio-final-deploy | Out-Null
+            Write-Host "Contenedor eliminado"
+          } catch {
+            Write-Host "No se eliminó ningún contenedor (posiblemente no existe)"
+          }
+
       - name: Desplegar contenedor de aplicación
+        shell: powershell
         run: |
-          docker run -d --name laboratorio-final-deploy -p 3000:3000 wainerock/devsecopslab-test:latest
+          Write-Host " Iniciando contenedor..."
+          docker run -p 3000:3000 --name laboratorio-final-deploy -d wainerock/devsecopslab-test:latest
 
-      - name: Esperar disponibilidad de la app
-        run: |
-          for i in {1..10}; do
-            if curl -s http://localhost:3000 > /dev/null; then
-              echo " Aplicación disponible"
-              exit 0
-            fi
-            echo " Esperando..."
-            sleep 5
-          done
-          echo " La app no respondió a tiempo"
-          exit 1
+      - name: Escanear con OWASP ZAP (DAST)
+        uses: zaproxy/action-baseline@v0.11.0
+        with:
+          target: 'http://localhost:3000/'
+          fail_action: false
+          # rules_file_name: '' ##
+          cmd_options: '-config replacer.full_list(0).enabled=false'
 
-      - name: Crear directorio de trabajo para ZAP
-        run: mkdir -p ${{ github.workspace }}
-
-      - name: Ejecutar ZAP Baseline Scan con Docker
-        run: |
-          docker run --network host \
-            -v ${{ github.workspace }}:/zap/wrk/:rw \
-            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
-            -t http://localhost:3000 \
-            -r zap-report.html \
-            -I
-      - name: Validar resultados ZAP (falla si WARN-NEW > 0)
-        run: |
-          echo "📋 Revisando zap-output.log..."
-          cat zap-output.log
-          | tee "${{ github.workspace }}/zap-output.log"
-
-
-          # Extrae el número de WARN-NEW
-          WARN_NEW=$(grep 'WARN-NEW:' zap-output.log | awk '{print $3}')
-          echo "WARN-NEW detectados: $WARN_NEW"
-
-          if [ "$WARN_NEW" -gt 0 ]; 
-          then
-            echo "Pipeline fallado por presencia de WARN-NEW."
-            exit 1
-          else
-            echo "No se encontraron advertencias nuevas (WARN-NEW = 0)"
-          fi
-      - name: Eliminar contenedor de aplicación
+      - name: Eliminar contenedor de aplicación (cleanup)
         if: always()
-        run: docker rm -f laboratorio-final-deploy || true
+        shell: powershell
+        run: |
+          Write-Host "Eliminando contenedor laboratorio-final-deploy..."
+          docker rm -f laboratorio-final-deploy | Out-Null
+
+    # DAST:
+    #   needs: SCANDOCKER
+    #   runs-on: self-hosted
+
+    #   steps:
+    #   - name: Desplegar contenedor de aplicación
+    #     run: |
+    #       docker run -d --name laboratorio-final-deploy -p 3000:3000 wainerock/devsecopslab-test:latest
+
+    #   - name: Esperar disponibilidad de la app
+    #     run: |
+    #       for i in {1..10}; do
+    #         if curl -s http://localhost:3000 > /dev/null; then
+    #           echo " Aplicación disponible"
+    #           exit 0
+    #         fi
+    #         echo " Esperando..."
+    #         sleep 5
+    #       done
+    #       echo " La app no respondió a tiempo"
+    #       exit 1
+
+    #   - name: Crear directorio de trabajo para ZAP
+    #     run: mkdir -p ${{ github.workspace }}
+
+    #   - name: Ejecutar ZAP Baseline Scan con Docker
+    #     run: |
+    #       docker run --network host \
+    #         -v ${{ github.workspace }}:/zap/wrk/:rw \
+    #         ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
+    #         -t http://localhost:3000 \
+    #         -r zap-report.html \
+    #         -I
+    #   - name: Validar resultados ZAP (falla si WARN-NEW > 0)
+    #     run: |
+    #       echo "📋 Revisando zap-output.log..."
+    #       cat zap-output.log
+    #       | tee "${{ github.workspace }}/zap-output.log"
+
+
+    #       # Extrae el número de WARN-NEW
+    #       WARN_NEW=$(grep 'WARN-NEW:' zap-output.log | awk '{print $3}')
+    #       echo "WARN-NEW detectados: $WARN_NEW"
+
+    #       if [ "$WARN_NEW" -gt 0 ]; 
+    #       then
+    #         echo "Pipeline fallado por presencia de WARN-NEW."
+    #         exit 1
+    #       else
+    #         echo "No se encontraron advertencias nuevas (WARN-NEW = 0)"
+    #       fi
+    #   - name: Eliminar contenedor de aplicación
+    #     if: always()
+    #     run: docker rm -f laboratorio-final-deploy || true
 
